/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Noeman
 */
public class viewBook extends javax.swing.JFrame {
    public Doctor d;
    public Patient p;
    
    private int cDay;
    private int cTime;
    public void catchObj(Doctor d, Patient p){
        this.d = d;
        this.p = p;
    }
    public void view(ArrayList <String> a){
        titleNote.setText(p.getName()+"'s Appointments");
        for(int i = 0; i < 10; i++){
             bookedT.setValueAt(null, i,0);
            
        }
        for(int i = 0; i < a.size(); i++){
            bookedT.setValueAt(a.get(i), i,0);
            
        }
            
        
        
    }
    /**
     * Creates new form viewBook
     */

    public viewBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleNote = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookedT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleNote.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bookedT.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        bookedT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookedT.setRowHeight(35);
        jScrollPane2.setViewportView(bookedT);
        if (bookedT.getColumnModel().getColumnCount() > 0) {
            bookedT.getColumnModel().getColumn(0).setResizable(false);
        }

        jButton1.setText("Cancel Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleNote, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(titleNote, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JComboBox cxlCB = new JComboBox(p.getCappointments().toArray()); 
        int input = JOptionPane.showConfirmDialog(this,cxlCB,"Select Appointment", JOptionPane.DEFAULT_OPTION);
        if(input == JOptionPane.OK_OPTION) {     
        String i = (String)cxlCB.getSelectedItem();
                System.out.println(i);
                System.out.println(input);
                
                String [] D = new String [6]; 
        D[0] = "Saturday"; 
        D[1] = "Sunday"; 
        D[2] = "Monday"; 
        D[3] = "Tuesday"; 
        D[4] = "Wedensday"; 
        D[5] = "Thursday"; 
        String [] t = new String[6]; 
        t [0] = "9-11";
        t [1] = "11-1";
        t [2] = "1-3";
        t [3] = "3-5";
        t [4] = "5-7";
        t [5] = "7-9"; 
        for(int l = 0; l <6; l++){
            for(int j = 0; j<6; j++){
                
        String temp = D[l]+t[j];
                if(temp.equals(i)){
                    this.cDay = l;
                    this.cTime = j;
                }
            }
        }
        this.p.cancelBook(d, cDay, cTime);
                JOptionPane.showMessageDialog(this, i + "\n is Canceled!", "Cancel Info", JOptionPane.INFORMATION_MESSAGE);
                 for(int j = 0; j < 10; j++){
             bookedT.setValueAt(null, j,j);
             
            dispose(); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookedT;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titleNote;
    // End of variables declaration//GEN-END:variables
}
